import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { isValidUrl } from './EvidenceSection';

/**
 * Property-based tests for URL validation
 *
 * **Validates: Requirements 3.2**
 */

describe('EvidenceSection - Property Tests', () => {
  // ─── Property 8: URL validation correctness ─────────────────────────
  //
  // For any string input, the URL validator shall return true if and only if
  // the string is a well-formed URL (parseable by the URL constructor).

  describe('Property 8: URL validation correctness', () => {
    it('should return true for any well-formed URL generated by fc.webUrl()', () => {
      fc.assert(
        fc.property(fc.webUrl(), (url) => {
          expect(isValidUrl(url)).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it('should return false for strings that are not valid URLs', () => {
      const invalidUrlArb = fc.string().filter((s) => {
        try {
          new URL(s);
          return false;
        } catch {
          return true;
        }
      });

      fc.assert(
        fc.property(invalidUrlArb, (s) => {
          expect(isValidUrl(s)).toBe(false);
        }),
        { numRuns: 100 }
      );
    });

    it('should be equivalent to URL constructor parseability for any string', () => {
      fc.assert(
        fc.property(fc.string(), (s) => {
          let expected: boolean;
          try {
            new URL(s);
            expected = true;
          } catch {
            expected = false;
          }
          expect(isValidUrl(s)).toBe(expected);
        }),
        { numRuns: 100 }
      );
    });
  });
});
